# build with `scons --debug-build` for debug.
AddOption(
    '--debug-build',
    action='store_true',
    help='debug build',
    default=False)

env = Environment()

if GetOption('debug_build'):
    env.Append(CCFLAGS = '-g')
    env.Append(LINKFLAGS = '-g')

    variant_dir = 'build/debug'
else:
    variant_dir = 'build/release'

SConscript(dirs='.', src_dir='src',
           variant_dir=variant_dir,
           duplicate=True,
           exports="env")
